version: 2

project_name: nativefire

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: "386"
    main: ./main.go
    binary: nativefire
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

universal_binaries:
  - replace: true

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew tap configuration
brews:
  - name: nativefire
    repository:
      owner: clix-so
      name: nativefire
    directory: homebrew
    homepage: https://github.com/clix-so/nativefire
    description: "🚀 Simplify Firebase setup in native development environments"
    license: MIT
    test: |
      system "#{bin}/nativefire --version"
    install: |-
      bin.install "nativefire"

# npm package configuration for GitHub releases
release:
  github:
    owner: clix-so
    name: nativefire
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## What's Changed in v{{ .Version }}
    
    Welcome to this new release of NativeFire! 🚀
  footer: |
    ## Download
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew install clix-so/nativefire/nativefire
    ```
    
    ### npm/npx (All platforms)
    ```bash
    npx nativefire@latest configure
    # or install globally
    npm install -g nativefire
    ```
    
    ### Direct Download
    Download the appropriate binary for your platform from the assets below.
    
    ---
    
    **Full Changelog**: https://github.com/clix-so/nativefire/compare/{{ .PreviousTag }}...{{ .Tag }}

# Docker images (optional)
dockers:
  - image_templates:
      - "ghcr.io/clix-so/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/clix-so/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"