blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/clix-so/nativefire/wiki
    about: Check our documentation for guides and tutorials
  - name: 💬 Discussions
    url: https://github.com/clix-so/nativefire/discussions  
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/clix-so/nativefire/security/advisories/new
    about: Report security vulnerabilities privately