# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MyApp' do
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp
  pod 'Alamofire', '~> 5.6'
  
  target 'MyAppTests' do
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyAppUITests' do
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
    # Pods for testing
  end
end