name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Verify Firebase CLI
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        firebase --version || echo "Firebase CLI not found in PATH"

    - name: Run tests
      run: |
        echo "Testing each package individually..."
        for pkg in $(go list ./... | grep -E "(cmd|internal)"); do
          echo "Testing package: $pkg"
          go test -short -timeout=5m "$pkg" || exit 1
        done
        echo "All tests completed successfully"

    - name: Extract version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Update package.json version
      run: |
        VERSION="${{ steps.version.outputs.VERSION }}"
        VERSION=${VERSION#v}
        sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" package.json
        echo "Updated package.json to version: $VERSION"

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}